[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "rust"
language-servers = ["ra-multiplex"]

[language-server.ra-multiplex]
name = "ra-multiplex"
command = "ra-multiplex"


[[language]]
name = "jinja"
file-types = ["j2"]
language-servers = ["tailwindcss-ls", "vscode-html-language-server"]


[[language]]
name = "tera"
file-types = ["tera"]
language-servers = ["tailwindcss-ls", "vscode-html-language-server"]

[[language]]
name = "javascript"
shebangs = ["node"]
roots = ["package.json"]
file-types = ["js"]
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-serve",
  "vscode-langservers-extracted",
]

[[language]]
name = "typescript"
shebangs = ["node"]
roots = ["tsconfig.json", "package.json"]
file-types = ["ts"]
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-serve",
  "vscode-langservers-extracted",
]

[[language]]
name = "jsx"
shebangs = ["node"]
roots = ["package.json"]
file-types = ["jsx"]
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-serve",
  "tailwindcss-ls",
]

[[language]]
name = "tsx"
shebangs = ["node"]
roots = ["tsconfig.json", "package.json"]
file-types = ["tsx"]
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-serve",
  "typescript-language-server",
]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]


[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["pylsp"]
auto-format = true

[language-server.pylsp]
command = "pylsp"

[language-server.pylsp.config.pylsp.plugins.pycodestyle]
ignore = ["E501", "W503"]
