[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { userLanguages = { jinja = "html" } }

[[language]]
name = "jinja"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]
auto-format = true


[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]
auto-format = true
