[language-server.gpt]
command = "helix-gpt"
args = ["--handler", "codeium"]

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { userLanguages = { jinja = "html" } }

[[language]]
name = "jinja"
language-servers = ["vscode-html-language-server", "tailwindcss-ls", "gpt"]
auto-format = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls", "gpt"]
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "gpt"]

[language-server.rust-analyzer.config.check]
command = "clippy"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "javascript"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc"]
file-types = ["js"]
language-servers = ["deno-lsp"]
auto-format = true

[[language]]
name = "typescript"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc"]
file-types = ["ts"]
language-servers = ["deno-lsp", "gpt"]
auto-format = true

[[language]]
name = "jsx"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "gpt"]
file-types = ["jsx"]
language-servers = ["deno-lsp"]
auto-format = true

[[language]]
name = "tsx"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "gpt"]
file-types = ["tsx"]
language-servers = ["deno-lsp"]
auto-format = true

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
environment = { NO_COLOR = "1" }

[language-server.deno-lsp.config.deno]
enable = true
suggest = { completeFunctionCalls = false, imports = { hosts = { "https://deno.land" = true } } }

[[language]]
name = "python"
language-servers = ["pyright", "ruff", "gpt"]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
config = { settings = { args = ["server"] } }
